'use strict';

/**
 * @fileoverview Smart Functions - Auto Test Generator
 *
 * Generates test cases automatically based on smart contract ABI
 * and function signatures.
 *
 * @module smart-functions/auto-test
 */

/**
 * AutoTestGenerator class.
 * Generates unit test scaffolding for smart contract functions based on their ABI.
 */
class AutoTestGenerator {
  /**
   * Creates a new AutoTestGenerator instance.
   * @param {object} [options={}] - Configuration options.
   * @param {string} [options.framework='jest'] - Test framework to target ('jest' or 'mocha').
   * @param {boolean} [options.includeEdgeCases=true] - Whether to include edge-case tests.
   */
  constructor(options = {}) {
    this.options = Object.assign(
      {
        framework: 'jest',
        includeEdgeCases: true
      },
      options
    );
  }

  /**
   * Validates an ABI array.
   * @param {*} abi - ABI to validate.
   * @throws {Error} When abi is not a non-empty array.
   */
  _validateAbi(abi) {
    if (!Array.isArray(abi) || abi.length === 0) {
      throw new Error('abi must be a non-empty array');
    }
  }

  /**
   * Generates a default test value for a Solidity type.
   * @param {string} type - Solidity type string.
   * @returns {string} JavaScript representation suitable for use in test code.
   */
  _defaultValueForType(type) {
    if (type.startsWith('uint') || type.startsWith('int')) {
      return '42';
    }
    if (type === 'address') {
      return "'0x0000000000000000000000000000000000000001'";
    }
    if (type === 'bool') {
      return 'true';
    }
    if (type === 'string') {
      return "'hello'";
    }
    if (type.endsWith('[]')) {
      return '[]';
    }
    return 'null';
  }

  /**
   * Generates test cases for a single ABI function entry.
   * @param {object} fn - ABI function entry.
   * @param {string} contractName - Name of the contract.
   * @returns {string} Generated test code block.
   */
  _generateFunctionTest(fn, contractName) {
    const args = (fn.inputs || []).map(input => this._defaultValueForType(input.type));
    const argStr = args.join(', ');
    const fnCall = `contract.${fn.name}(${argStr})`;

    const lines = [
      `  describe('${fn.name}', () => {`,
      "    it('should execute without reverting', async () => {",
      '      // Arrange',
      `      // TODO: deploy ${contractName} contract`,
      '      // Act',
      `      const result = await ${fnCall};`,
      '      // Assert',
      '      expect(result).toBeDefined();',
      '    });'
    ];

    if (this.options.includeEdgeCases && fn.inputs && fn.inputs.length > 0) {
      lines.push("    it('should handle invalid inputs gracefully', async () => {");
      lines.push('      // TODO: supply invalid/boundary inputs');
      lines.push(`      await expect(${fnCall}).resolves.toBeDefined();`);
      lines.push('    });');
    }

    lines.push('  });');
    return lines.join('\n');
  }

  /**
   * Generates a complete test file from an ABI.
   * @param {object[]} abi - Contract ABI array.
   * @param {string} [contractName='Contract'] - Name of the contract.
   * @returns {object} Result with status, data (test code), and metadata.
   */
  generateTests(abi, contractName = 'Contract') {
    try {
      this._validateAbi(abi);

      const functions = abi.filter(entry => entry.type === 'function');
      const testBlocks = functions.map(fn => this._generateFunctionTest(fn, contractName));

      const header = [
        "'use strict';",
        '',
        '/**',
        ` * Auto-generated tests for ${contractName}`,
        ' * Generated by SmartBrain AutoTestGenerator',
        ' */',
        '',
        `describe('${contractName}', () => {`
      ].join('\n');

      const footer = '});\n';
      const testCode = [header, testBlocks.join('\n\n'), footer].join('\n\n');

      return {
        status: 'ok',
        data: {
          contractName,
          functionCount: functions.length,
          testCode
        },
        metadata: {
          generatedAt: new Date().toISOString(),
          framework: this.options.framework,
          version: '1.0.0'
        }
      };
    } catch (err) {
      return {
        status: 'error',
        data: null,
        metadata: {
          error: err.message,
          generatedAt: new Date().toISOString()
        }
      };
    }
  }
}

module.exports = AutoTestGenerator;
